name: Deploy to GitHub Pages

on:
  push:
    branches:
      - portfolio-page

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: npm install
      - name: Configure Git user
        run: |
          git config --global user.email "ritwickrajmakhal11@gmail.com"
          git config --global user.name "ritwickrajmakhal"
      - run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
